# Generated by Django 2.0.6 on 2019-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3cwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default='2019-02-21'),
        ),
    ]
